### ISSUE TITLE
Could not find download.sh

### ISSUE THREAD

**Issue by czhang0701** [theislab/2020_Mayr#1]
I cannot find the download.sh file mentioned in the documentation, and it is impossible to test other scripts. Please fix that.

**Comment by lkmklsmn** [comment]
You are right!

We will fix this asap.

Apologies.

**Comment by lkmklsmn** [comment]
Hi @czhang0701 I have added a link to download the files in the README. You wont use a download script but use the download link manually. 

Let me know if you have any more questions.
