### ISSUE TITLE
Raw count data

### ISSUE THREAD

**Issue by iandriver** [theislab/2020_Mayr#2]
The integrated_human_dataset.h5ad does not have any raw count data or the size factors, so it's impossible to get raw count data from adata.raw. munich_cohort_human_dataset.h5ad has adata.layers['counts'], would it be possible to get the integrated data with the same?

**Comment by lkmklsmn** [comment]
Hi Ian, thanks for pointing this out! We are currently updating all code to accompany our updated version of the manuscript. We will make sure to correct this in the updated version of the analysis code (to be released soon).

**Comment by iandriver** [comment]
Saw the update a while ago. Super easy to get raw data now. Closing now. Thanks!
